import turtle
import tkinter as tk

def l ():
    turt.right(90)
    turt.fd(100)
    turt.left(90)
    turt.fd(50)
    turt.penup()
    turt.fd(20)
    turt.left(90)
    turt.fd(100)
    turt.right(90)
    turt.pendown()

def u():
    turt.right(90)
    turt.fd(75)
    turt.circle(25, 180)
    turt.fd(75)
    turt.penup()
    turt.right(90)
    turt.fd(20)
    turt.pendown()

def c():
    turt.penup()
    turt.fd(50)
    turt.pendown()
    turt.right(180)
    turt.circle(50, 180)
    turt.penup()
    turt.fd(20)
    turt.left(90)
    turt.fd(100)
    turt.right(90)
    turt.pendown()

def a():
    turt.penup()
    turt.fd(50)
    turt.pendown()
    turt.right(115)
    turt.fd(115)
    turt.penup()
    turt.bk(60)
    turt.left(115)
    turt.pendown()
    turt.fd(25)
    turt.penup()
    turt.left(90)
    turt.fd(50)
    turt.pendown()
    turt.right(180)
    turt.fd(100)
    turt.penup()
    turt.left(90)
    turt.fd(20)
    turt.left(90)
    turt.fd(100)
    turt.right(90)
    turt.pendown()

def s():
    turt.penup()
    turt.fd(50)
    turt.pendown()
    turt.bk(25)
    turt.left(180)
    turt.circle(25, 180)
    turt.left(180)
    turt.circle(25, -180)
    turt.bk(25)
    turt.penup()
    turt.fd(70)
    turt.left(90)
    turt.fd(100)
    turt.right(90)
    turt.pendown()

def v():
    turt.right(65)
    turt.fd(115)
    turt.left(155)
    turt.fd(100)
    turt.penup()
    turt.right(90)
    turt.fd(20)
    turt.pendown()

def i():
    turt.right(90)
    turt.fd(100)
    turt.penup()
    turt.left(180)
    turt.fd(100)
    turt.right(90)
    turt.fd(20)
    turt.pendown()

def t():
    turt.fd(50)
    turt.bk(25)
    turt.right(90)
    turt.fd(100)
    turt.penup()
    turt.left(180)
    turt.fd(100)
    turt.right(90)
    turt.fd(70)
    turt.pendown()

def o():
    turt.penup()
    turt.right(90)
    turt.fd(100)
    turt.left(90)
    turt.fd(20)
    turt.pendown()
    turt.circle(50, 360)
    turt.penup()
    turt.fd(70)
    turt.left(90)
    turt.fd(100)
    turt.right(90)
    turt.pendown()

def r():
    turt.penup()
    turt.right(90)
    turt.fd(50)
    turt.left(90)
    turt.pendown()
    turt.circle(25, 180)
    turt.left(90)
    turt.fd(100)
    turt.bk(50)
    turt.left(25)
    turt.fd(55)
    turt.penup()
    turt.left(65)
    turt.fd(20)
    turt.left(90)
    turt.fd(100)
    turt.right(90)
    turt.pendown()

def h():
    turt.right(90)
    turt.fd(100)
    turt.bk(50)
    turt.left(90)
    turt.fd(50)
    turt.right(90)
    turt.fd(50)
    turt.bk(100)
    turt.penup()
    turt.left(90)
    turt.fd(20)
    turt.pendown()

def p():
    turt.penup()
    turt.right(90)
    turt.fd(50)
    turt.left(90)
    turt.pendown()
    turt.circle(25, 180)
    turt.left(90)
    turt.fd(100)
    turt.penup()
    turt.left(90)
    turt.fd(45)
    turt.left(90)
    turt.fd(100)
    turt.right(90)
    turt.pendown()

def e():
    turt.fd(30)
    turt.bk(30)
    turt.right(90)
    turt.fd(50)
    turt.left(90)
    turt.fd(30)
    turt.bk(30)
    turt.right(90)
    turt.fd(50)
    turt.left(90)
    turt.fd(30)
    turt.penup()
    turt.fd(20)
    turt.left(90)
    turt.fd(100)
    turt.right(90)
    turt.pendown()


def lucas():
    l()
    u()
    c()
    a()
    s()
    turt.penup()
    global y
    y -= 120
    turt.goto(-300, y)
    turt.pendown()

def vitor():
    v()
    i()
    t()
    o()
    r()
    turt.penup()
    global y
    y -= 120
    turt.goto(-300, y)
    turt.pendown()

def loch():
    l()
    o()
    c()
    h()
    turt.penup()
    global y
    y -= 120
    turt.goto(-300, y)
    turt.pendown()

def pereira():
    p()
    e()
    r()
    e()
    i()
    r()
    a()
    turt.penup()
    global y
    y -= 120
    turt.goto(-300, y)
    turt.pendown()

root = tk.Tk()
canvas = tk.Canvas(master = root, width = 700, height = 600)
turtle_screen = turtle.TurtleScreen(canvas)
turtle_screen.bgcolor("black")
canvas.pack()

menu=tk.Menu(root)
menu.add_command(label="Lucas",command=lucas)
menu.add_command(label="Vitor",command=vitor)
menu.add_command(label="Loch",command=loch)
menu.add_command(label="Pereira",command=pereira)
root.configure(menu=menu)

turt = turtle.RawTurtle(turtle_screen)
turt.pencolor("#ffffff")
turt.shape('arrow')
y = 250  # Initial Position of Y which will be decremented to maintain the default spacing between lines
turt.penup()
turt.goto(-300, y)
turt.pendown()
turt.showturtle()
turt.speed(10)
turt.pensize(5)

root.mainloop()